apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-todo-api
  namespace: default
  labels:
    app: rust-todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-todo-api
  template:
    metadata:
      labels:
        app: rust-todo-api
    spec:
      containers:
        - name: rust-todo-api
          image: "192.168.82.102:5000/todo-app-backend:latest"
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
