apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  KC_DB: postgres
  KC_HOSTNAME: keycloak.local
  KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/tls.crt
  KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/tls.key
  KC_HTTP_ENABLED: "false"
  KC_HOSTNAME_STRICT: "true"
  KC_HOSTNAME_STRICT_HTTPS: "true"
