apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
type: Opaque
stringData:
  KC_DB_USERNAME: todo_user
  KC_DB_PASSWORD: todo_password
  KC_DB_URL: jdbc:postgresql://my-postgres-rw:5432/todo_db
