#!/bin/bash

# This script configures passwordless SSH access to Multipass VMs for Ansible.

# --- Configuration ---
# Your public SSH key file
# IMPORTANT: Make sure this path points to your PUBLIC key (.pub)
PUBLIC_KEY_FILE="$HOME/.ssh/id_ed25519.pub"

# Names of your Multipass instances
# Add or remove names as needed to match your setup
INSTANCE_NAMES=("controller-node" "worker-1")

# --- Script Logic ---

# 1. Check if the public key file exists
if [ ! -f "$PUBLIC_KEY_FILE" ]; then
    echo "ERROR: Public key file not found at $PUBLIC_KEY_FILE"
    echo "Please make sure the path is correct."
    exit 1
fi

# 2. Read the public key content
PUBLIC_KEY_CONTENT=$(cat "$PUBLIC_KEY_FILE")
if [ -z "$PUBLIC_KEY_CONTENT" ]; then
    echo "ERROR: The public key file is empty."
    exit 1
fi

echo "Public key successfully read."
echo ""

# 3. Loop through each instance and configure SSH
for name in "${INSTANCE_NAMES[@]}"; do
    echo "--- Configuring SSH for instance: $name ---"

    # Check if the instance is running
    if ! multipass info "$name" | grep -q "State: *Running"; then
        echo "WARNING: Instance '$name' is not running. Skipping."
        echo ""
        continue
    fi

    # Use multipass exec to run the configuration commands on the instance
    # The commands are passed as a single string to 'bash -c'
    multipass exec "$name" -- bash -c "
        echo 'Creating .ssh directory...'
        mkdir -p /home/ubuntu/.ssh

        echo 'Adding public key to authorized_keys...'
        # Using a temporary file to avoid issues with shell interpretation of the key
        echo '$PUBLIC_KEY_CONTENT' >> /home/ubuntu/.ssh/authorized_keys

        echo 'Setting correct permissions...'
        chmod 700 /home/ubuntu/.ssh
        chmod 600 /home/ubuntu/.ssh/authorized_keys
        chown -R ubuntu:ubuntu /home/ubuntu/.ssh

        echo 'Configuration for $name complete.'
    "
    echo "--- Finished for instance: $name ---"
    echo ""
done

echo "All instances have been configured."
echo "You should now be able to run your Ansible playbook."

## This script updates the Ansible inventory file with the current IPs of Multipass instances
## This is the next step after setting up SSH keys


set -e

# Get the directory of the script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Path to the inventory file
INVENTORY_FILE="$SCRIPT_DIR/ansible/inventory"

# Get instance information from multipass
INSTANCES=$(multipass list --format json)

# Start with a clean inventory file
cat > "$INVENTORY_FILE" << EOL
# This inventory was auto-generated by update_inventory.sh

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/Users/gis/.ssh/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

EOL

# Process controller node
CONTROLLER_IP=$(echo "$INSTANCES" | jq -r '.list[] | select(.name=="controller-node") | .ipv4[0]')
if [ -n "$CONTROLLER_IP" ]; then
    echo "[controller]" >> "$INVENTORY_FILE"
    echo "controller-node ansible_host=$CONTROLLER_IP" >> "$INVENTORY_FILE"
fi

# Process worker nodes
WORKER_IPS=$(echo "$INSTANCES" | jq -r '.list[] | select(.name|test("^worker-")) | .ipv4[0]')
if [ -n "$WORKER_IPS" ]; then
    echo "
[workers]" >> "$INVENTORY_FILE"
    COUNT=0
    for ip in $WORKER_IPS; do
        echo "worker-$COUNT ansible_host=$ip" >> "$INVENTORY_FILE"
        COUNT=$((COUNT + 1))
    done
fi

# Add the public key to each host
PUB_KEY=$(cat ~/.ssh/id_ed25519.pub)

ALL_HOSTS=$(echo "$INSTANCES" | jq -r '.list[].ipv4[0]')

for host in $ALL_HOSTS; do
    echo "Configuring SSH for $host"
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@$host "\
        mkdir -p ~/.ssh && \
        chmod 700 ~/.ssh && \
        echo \"$PUB_KEY\" >> ~/.ssh/authorized_keys && \
        chmod 600 ~/.ssh/authorized_keys && \
        sort -u ~/.ssh/authorized_keys -o ~/.ssh/authorized_keys"
done

echo "Inventory file updated successfully."
