---
- name: Get k3s token from local file
  local_action: "command cat /tmp/k3s_token"
  register: k3s_token
  become: false
  changed_when: false

- name: Join worker node to cluster
  shell: "curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars[groups['control'][0]]['ansible_host'] }}:6443 K3S_TOKEN={{ k3s_token.stdout }} sh -"
  args:
    creates: /usr/local/bin/k3s