---
# tasks file for join-k3s

# It is assumed that the k3s_url and k3s_token are passed as extra variables.
#
# Example:
# ansible-playbook playbook.yml --extra-vars "k3s_url=https://<control_plane_ip>:6443 k3s_token=<token>"
#
# To get the token from the control plane, run the following command on the control plane:
# sudo cat /var/lib/rancher/k3s/server/node-token

- name: Join worker node to cluster
  shell: "curl -sfL https://get.k3s.io | K3S_URL={{ k3s_url }} K3S_TOKEN={{ k3s_token }} sh -"
  args:
    creates: /usr/local/bin/k3s
