---
- name: Prepare all nodes
  hosts: all
  gather_facts: true
  become: true
  roles:
    - role: install-docker

- name: Harden all nodes
  hosts: all
  become: true
  vars:
    ubtu24cis_rule_5_2_4: false
  roles:
    - role: hardening
