---
- name: Prepare all nodes
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Ensure docker packages are installed
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present

- name: Configure control plane
  hosts: control
  become: true
  roles:
    - role: install-k3s
      tags: k3s

- name: Configure worker nodes
  hosts: workers
  become: true
  roles:
    - role: join-k3s
      tags: k3s
