---
- name: Install k3s on control plane
  shell: "curl -sfL https://get.k3s.io | sh -"
  args:
    creates: /usr/local/bin/k3s

- name: Fetch the k3s token
  become: true
  fetch:
    src: /var/lib/rancher/k3s/server/node-token
    dest: /tmp/k3s_token
    flat: yes

- name: Create .kube directory for ubuntu user
  file:
    path: "/home/ubuntu/.kube"
    state: directory
    owner: "ubuntu"
    group: "ubuntu"
    mode: "0755"

- name: Copy k3s config to ubuntu user
  copy:
    src: "/etc/rancher/k3s/k3s.yaml"
    dest: "/home/ubuntu/.kube/config"
    remote_src: true
    owner: "ubuntu"
    group: "ubuntu"
    mode: "0600"

- name: Adjust k3s config to be accessible from outside the VM
  replace:
    path: "/home/ubuntu/.kube/config"
    regexp: 'https://127.0.0.1:6443'
    replace: 'https://{{ ansible_host }}:6443'