---
- name: Install k3s on control plane
  shell: "curl -sfL https://get.k3s.io | sh -"
  args:
    creates: /usr/local/bin/k3s

- name: Get k3s token
  command: "sudo cat /var/lib/rancher/k3s/server/node-token"
  register: k3s_token
  changed_when: false

- name: Store k3s token locally
  local_action: "copy content={{ k3s_token.stdout }} dest=/tmp/k3s_token"
  become: false